v0.1.0 - minor version change - 2015-08-13
------------------------------------------
* edits on java files


v0.0.8 - minor changes - 2015-07-21
-----------------------------------
* changed classMap in ExecS to protected
	** allows sub-classes to clear the map when using auto-gen run script features
* removed deprecated classes and options


v0.0.7 - feature add - 2015-07-12
---------------------------------
* added execs.autogenerate.registered to Gen_RunScripts
* removed default class map in Gen_RunScripts
* added getScriptName() to ExecutableService for customization of run script generation


v0.0.6 - feature add - 2015-07-01
---------------------------------
* added factory for CLI option generation
  ** changed StandardOptions to use factory rather than instantiate locally
* added Gen_RunScripts to generate run scripts for Executable services
* added "stg-file" option to standard options
* fixed bug in ExecS_Cli not accepting ExecS_CliOption but only StandardOptions
* marked some StandardOptions as deprecated since they are rather specific, to be removed in next release
  ** all ZK_ options
  ** all WS_ options
  ** DO_RECONNECT
  ** all EVENT_ options
  ** ASCII_DOCTOR
* added shell scripts for script generation
  ** gen-run-script.sh to generate run scripts
  ** rebase.sh to rebase existing scripts
* refactored and changed the ClassFinder
  ** now in package cf with separated classes for different functionality
  ** deprecated the old ClassFinder class, to be removed in next release
* changed printouts for ExecS
  ** added an STG for all major printouts (usage, lists)
  ** moved all printouts to STG
* added services to generate shell scripts
  ** Gen_RunSh - to generate a shell script that uses Gen_RunScripts to generate run scripts
  ** Gen_RebaseSh - to generate a shell script that can rebase run scripts


v0.0.5 - feature add - 2015-06-23
---------------------------------
* renamed classes
* rewrite of service executor, removed CLI and wrote internal CLI
* changed CLI to use Apache Common CLI 1.3.1
* added CLI option interface and moved options into Standard Enum implementation of the interface
* added tests
* experimental: added logging for CLI, might remove that and use strin return instead
* added FigletShutdown :)


v0.0.4 - maintenance - 2015-06-19
---------------------------------
* clean up, test file rename


v0.0.3 - feature add - 2015-06-18
---------------------------------
* moved to maven
* moved into own repo at Github
* added simple CLI parser
* added standard options
* added getCLI() and getName() with default implementations to executale


v0.0.2 - feature add - 2014-06-25
---------------------------------
* added CLI interface using Apache Common CLI
* externalised use of jar and package filters (via CLI)
* changed internal behviour for new CLI
* sub-classes can now overwrite the jar/package filters
* changed help/list screen print outs
* added test to not show named executables


v0.0.1 - initial release - 2014-06-10
-------------------------------------
* initial release